package com.pbrockt.tagebuch.ui.calendar

import java.time.LocalDate

val motivationalQuotes = listOf(
    // Tagebuch & Schreiben
    "Das Leben wird vorwärts gelebt, aber rückwärts verstanden.",
    "Jeder Tag ist eine neue Seite in deiner Geschichte.",
    "Wer schreibt, der bleibt – auch in der Erinnerung.",
    "Ein Tagebuch ist der ehrlichste Freund, den man haben kann.",
    "Schreiben heißt, mit sich selbst sprechen.",
    "In Worten steckt mehr Magie als in jedem Zaubertrank.",
    "Deine Geschichte ist es wert, erzählt zu werden.",
    "Was du aufschreibst, vergisst du nie ganz.",
    "Ein Tagebuch ist ein Fenster in die eigene Seele.",
    "Schreibe, was dich bewegt – und du wirst dich selbst besser verstehen.",
    "Jedes Wort, das du schreibst, ist ein Schritt zu dir selbst.",
    "Das Papier nimmt alles geduldig an.",
    "Wer seine Gedanken aufschreibt, gibt ihnen ein Zuhause.",
    "Dein Tagebuch vergisst nichts und verrät nichts.",
    "Die Feder ist mächtiger als das Schwert.",
    // Leben & Tage
    "Genieße die kleinen Dinge – eines Tages wirst du erkennen, dass sie die großen waren.",
    "Jeder Morgen ist ein neuer Anfang.",
    "Es sind die kleinen Momente, die das große Leben ausmachen.",
    "Der beste Zeitpunkt, glücklich zu sein, ist jetzt.",
    "Gestern ist Geschichte, morgen ist Geheimnis, heute ist ein Geschenk.",
    "Das Schönste am Heute ist, dass es immer noch kommen kann.",
    "Jeder Sonnenuntergang gibt uns eine Chance, neu zu beginnen.",
    "Das Leben lächelt uns an – wir müssen nur zurücklächeln.",
    "Tue jeden Tag etwas, das dich deinem Traum näherbringt.",
    "Die schönsten Erinnerungen entstehen oft ganz unbemerkt.",
    "Lebe so, dass du dich morgen noch über heute freuen kannst.",
    "Jeder Tag bringt eine neue Möglichkeit, glücklich zu sein.",
    "Ein guter Tag beginnt mit einem guten Gedanken.",
    "Nicht die Jahre in deinem Leben zählen, sondern das Leben in deinen Jahren.",
    "Manchmal braucht man keinen großen Plan – nur den nächsten kleinen Schritt.",
    "Das Leben ist zu kurz für schlechte Laune.",
    "Ein Tag ohne Lächeln ist ein verlorener Tag.",
    "Manchmal ist der gewöhnlichste Tag der schönste.",
    "Die schönste Reise ist die zu sich selbst.",
    "Heute ist immer der beste Tag, um anzufangen.",
    // Gefühle & Stimmung
    "Gefühle sind keine Feinde – sie wollen nur gehört werden.",
    "Es ist okay, heute nicht okay zu sein.",
    "Jedes Gefühl ist erlaubt – kein Gefühl ist falsch.",
    "Nach dem Regen kommt die Sonne – und manchmal ein Regenbogen.",
    "Deine Gefühle sind real und sie sind wichtig.",
    "Sei sanft mit dir selbst an schlechten Tagen.",
    "Wenn du weinst, machst du Platz für neue Freude.",
    "Deine Emotionen machen dich menschlich und einzigartig.",
    "Auch ein grauer Tag hat seine eigene Schönheit.",
    "Lass die Gefühle fließen – und schreib sie auf.",
    "Traurigkeit ist auch ein Gefühl, das Platz verdient.",
    "Glück ist kein Zustand – es ist ein Augenblick.",
    "Wut, Trauer, Freude – sie alle gehören zum Leben.",
    "Manchmal ist der mutigste Satz: Heute ist es schwer.",
    "Nach dem Sturm kommt immer die Stille.",
    // Mut & Wachstum
    "Du bist mutiger, als du glaubst.",
    "Wachstum beginnt dort, wo die Komfortzone endet.",
    "Fehler sind der Beweis, dass du es versuchst.",
    "Aus jeder schwierigen Situation lernst du etwas über dich.",
    "Du musst nicht perfekt sein – du musst nur echt sein.",
    "Manchmal ist der erste Schritt der schwerste – und der wichtigste.",
    "Vertraue dem Prozess, auch wenn du das Ergebnis noch nicht siehst.",
    "Du hast bereits so viel geschafft, woran du einmal gezweifelt hast.",
    "Scheitern ist kein Rückschritt – es ist ein Umweg zum Ziel.",
    "Jeder Experte war einmal ein Anfänger.",
    "Die stärksten Bäume wachsen im stärksten Wind.",
    "Du bist nicht das, was dir passiert – du bist, wie du darauf reagierst.",
    "Kleine Fortschritte sind immer noch Fortschritte.",
    "Heute etwas Neues versuchen ist der beste Schritt vorwärts.",
    "Glaube an dich – besonders dann, wenn es schwer fällt.",
    "Herausforderungen zeigen dir, wie stark du bist.",
    "Der Weg entsteht beim Gehen.",
    "Manchmal braucht man Mut, um einfach so zu sein, wie man ist.",
    "Du wächst nicht trotz der schwierigen Zeiten, sondern durch sie.",
    "Der Unterschied zwischen Stolpern und Fallen ist, ob du aufstehst.",
    // Glück & Dankbarkeit
    "Glück ist oft ganz nah – man muss nur danach Ausschau halten.",
    "Dankbarkeit verwandelt das, was wir haben, in genug.",
    "Das Glück liegt im Kleinen: ein Lachen, eine Umarmung, ein sonniger Morgen.",
    "Sei dankbar für das, was du hast – und offen für das, was noch kommt.",
    "Freude ist ansteckend – teile sie großzügig.",
    "Das Schönste im Leben ist kostenlos: Lachen, Liebe, Zeit.",
    "Glücklich sein ist eine Entscheidung, die man jeden Tag neu treffen kann.",
    "Wer dankbar ist, sieht mehr Schönes in der Welt.",
    "Kleine Freuden sind das Fundament eines großen Glücks.",
    "Es gibt immer etwas, wofür man dankbar sein kann.",
    "Glück ist nicht das Ziel – es ist der Weg.",
    "Heute etwas Schönes bemerken – das ist schon ein guter Tag.",
    "Dankbarkeit ist das Gedächtnis des Herzens.",
    "Das Herz, das liebt und lacht, altert langsam.",
    "Manchmal ist das Schönste an einem Tag, einfach da zu sein.",
    // Für junge Menschen
    "Du bist einzigartig – genau so, wie du bist.",
    "Jeder Tag ist eine Chance, die beste Version von dir zu werden.",
    "Träume groß – und schreib sie auf.",
    "Du bist wichtiger, als du denkst.",
    "Das Leben hat so viele Abenteuer für dich bereit.",
    "Deine Fehler machen dich reicher an Erfahrung.",
    "Es ist wunderschön, jung zu sein und die Welt zu entdecken.",
    "Du musst nichts beweisen – du bist gut genug, so wie du bist.",
    "Lach viel, lebe neugierig, liebe ehrlich.",
    "Das Beste liegt noch vor dir.",
    "Deine Gedanken haben Kraft – also denk schön.",
    "Sei du selbst – alle anderen sind schon vergeben.",
    "Die Welt braucht genau dich – mit all deinen Eigenheiten.",
    "Du bist das Hauptkapitel in deiner eigenen Geschichte.",
    "Jeder Tag ist ein Geschenk – und du entscheidest, was du draus machst.",
    "Hab keine Angst davor, du selbst zu sein.",
    "Deine Neugier ist deine Superkraft.",
    "Heute ist ein guter Tag, um etwas Neues auszuprobieren.",
    "Du hast das Zeug dazu – fang einfach an.",
    "Jede große Reise beginnt mit dem ersten Schritt."
)

fun getDailyQuote(): String {
    val dayOfYear = LocalDate.now().dayOfYear
    return motivationalQuotes[dayOfYear % motivationalQuotes.size]
}
